name: ebay-config

# Trading API OAuth - https://developer.ebay.com/api-docs/static/oauth-tokens.html

# UPDATE the values in this file, before running the tests
api.sandbox.ebay.com:
    appid: MichaelS-MTGSingl-SBX-2f78bdb77-a434fc39
    certid: SBX-f78bdb77fa9c-81c0-420e-9ec5-68b9
    devid: bacfae5f-f1b9-47f7-a1da-8f67ecbe0553
    redirecturi: Michael_Surdous-MichaelS-MTGSin-smiepgnc

api.ebay.com:
    appid: <appid-from-developer-portal>
    certid: <certid-from-developer-portal>
    devid: <devid-from-developer-portal>
    redirecturi: <redirect_uri-from-developer-portal>