name: test-config

# https://developer.ebay.com/DevZone/SandboxUser/
# Register a sandbox test user and use that credentials here
sandbox-user:
    username: testuser_surdouskicards
    password: U32GExu4SJ2qjyt$$

# Register a production test user and use that credentials here - https://reg.ebay.com/reg/PartialReg
production-user:
    username: <production-username>
    password: <production-user-password>